#!/bin/bash
default_args=("-cpu" "max")

args=()
native_flag_found=false
debug=false

run_default () {
	if [[ $(grep -i Microsoft /proc/version) ]]; then
		echo -e "WSL Detected - Running QEMU for Windows"
		qemu-system-x86_64.exe -cdrom ../dist/x86_64/WallOS.iso "${default_args[@]}" "${args[@]}"
	else 
		qemu-system-x86_64 -cdrom ../dist/x86_64/WallOS.iso "${default_args[@]}" "${args[@]}"
	fi
}

run_with_debug () {
	qemu-system-x86_64 -cdrom ../dist/x86_64/WallOS.iso -s -S "${default_args[@]}" "${args[@]}"
}

run_native () {
	echo -e "Running native QEMU. This should only have an effect if you are using WSL.\nIf you run into an error, or a window does not open, try running again without --native."
	qemu-system-x86_64 -cdrom ../dist/x86_64/WallOS.iso "${default_args[@]}" "${args[@]}"
}

run_native_db () {
	echo -e "Running native QEMU. This should only have an effect if you are using WSL.\nIf you run into an error, or a window does not open, try running again without --native."
	qemu-system-x86_64 -cdrom ../dist/x86_64/WallOS.iso -s -S "${default_args[@]}" "${args[@]}"
}

./build64
echo -e "<------------Running QEMU------------->"

# Iterate over the command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -d|--debug)
            # Set the debug flag
            debug=true
            shift
            ;;
        -n|--native)
            # Set the native flag
            native_flag_found=true
            shift
            ;;
        *)
            # Append the argument to the args array
            args+=("$1")
            shift
            ;;
    esac
done

# Check the value of the native_flag_found variable outside the loop
if [ "$native_flag_found" = true ]; then
  	if [ "$debug" = true ]; then
		echo "Running with debug config. Connect using GDB on port \`localhost:1234\`"
		run_native_db
	else
		run_native
	fi
else
	if [ "$debug" = true ]; then
		echo "Running with debug config. Connect using GDB on port `localhost:1234`"
		run_with_debug
	else
		run_default
	fi
fi
