name: Test Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
          
    - name: Cache Docker Image
      id: cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.docker
        key: ${{ runner.os }}-docker-${{ hashFiles('**/*.Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build Docker Image
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        docker build ./buildenv -t wallos-buildenv
        docker save -o ~/.docker/wallos-buildenv.tar wallos-buildenv

    - name: Load Docker Image
      if: steps.cache.outputs.cache-hit == 'true'
      run: |
        docker load -i ~/.docker/wallos-buildenv.tar
        
    - name: Build OS
      run: |
        docker run --rm -v $PWD:/root/env wallos-buildenv

    - name: Upload ISO as artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: WallOS-iso
        path: ./dist/x86_64/WallOS.iso





